default_install_hook_types: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
        args:
          - --unsafe
      - id: check-symlinks
        stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
        args:
          - --maxkb=15000
      - id: detect-private-key
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: terraform-docs
        name: terraform docs
        entry: terraform-docs
        args: [terraform]
        language: system
        pass_filenames: false
        types: [file]

      - id: terraform-fmt
        name: terraform fmt
        entry: terraform fmt
        args: [terraform]
        language: system
        pass_filenames: false
        types: [file]
